const ADD_MESSAGE = "ADD_MESSAGE";
const DELETE_MESSAGE = "DELETE_MESSAGE";
const EDIT_MESSAGE = "EDIT_MESSAGE";
const LOCAL_MESSAGES = "LOCAL_MESSAGES";
const SET_LAST_MESSAGE = "SET_LAST_MESSAGE";
const ADD_USER = "ADD_USER";
const REMOVE_USER = "REMOVE_USER";
const LOCAL_USERS = "LOCAL_USERS";

export {ADD_MESSAGE, DELETE_MESSAGE, EDIT_MESSAGE, LOCAL_MESSAGES, SET_LAST_MESSAGE, ADD_USER, REMOVE_USER, LOCAL_USERS};